name: Publish
on:
  release:
    types: [published]
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout xero-ruby repo
        uses: actions/checkout@v4
        with:
          repository: XeroAPI/xero-ruby
          path: xero-ruby

      - name: Set up Ruby environment
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: '3.2.0'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install
        working-directory: xero-ruby

      - name: Publish to Ruby
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          gemspec_file=$(ls *.gemspec) 
          gem_file=$(gem build "$gemspec_file" | grep -o '[^ ]*\.gem')
          echo "$gem_file"
          gem push "$gem_file"
        working-directory: xero-ruby
